services:
  fastbot:
    image: andreasros/fastbot-ros2-real:real
    container_name: fastbot
    restart: always
    network_mode: host
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/lslidar
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - ./ros2_ws:/ros2_ws
    command: bash -lc "source /ros2_ws/install/setup.bash &&
                       ros2 launch fastbot_bringup bringup.launch.xml"

  fastbot_slam:
    image: andreasros/fastbot-ros2-slam-real:real
    container_name: fastbot_slam
    restart: always
    depends_on: [fastbot]
    network_mode: host
    volumes:
      - ./ros2_ws:/ros2_ws
    command: bash -lc "source /ros2_ws/install/setup.bash &&
                       ros2 launch fastbot_slam_real cartographer.launch.py"
