FROM ros:humble

# Install mapping stack (cartographer, slam_toolbox, etc.)
RUN apt-get update && apt-get install -y \
    ros-humble-cartographer-ros \
    ros-humble-slam-toolbox \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ros2_ws
COPY src/ ./src/
COPY ros2_entrypoint.sh /
RUN . /opt/ros/humble/setup.sh && colcon build
RUN chmod +x /ros2_entrypoint.sh

ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ["ros2", "launch", "fastbot_slam", "slam.launch.py"] # Change to your SLAM launch file
