version: "3.3"
services:
  fastbot-ros2-gazebo:
    image: andreasros/andreasros-cp22:fastbot-ros2-gazebo
    container_name: fastbot-ros2-gazebo
    environment:
      - DISPLAY=${DISPLAY}
      - GAZEBO_MODEL_PATH=/ros2_ws/install/fastbot_description/share:/ros2_ws/src/fastbot
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw


  fastbot-ros2-slam:
    image: andreasros/andreasros-cp22:fastbot-ros2-slam
    container_name: fastbot-ros2-slam
    depends_on:
      - fastbot-ros2-gazebo

  fastbot-ros2-webapp:
    image: andreasros/andreasros-cp22:fastbot-ros2-webapp
    container_name: fastbot-ros2-webapp
    depends_on:
      - fastbot-ros2-gazebo
      - fastbot-ros2-slam
    ports:
      - "7000:7000"
