FROM ros:humble

RUN apt-get update && apt-get install -y \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-xacro \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ros2_ws
COPY src/ ./src/
COPY ros2_entrypoint.sh /
RUN . /opt/ros/humble/setup.sh && colcon build
RUN chmod +x /ros2_entrypoint.sh

ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ["ros2", "launch", "fastbot_gazebo", "one_fastbot_room.launch.py"]