FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential python3-colcon-common-extensions python3-vcstool \
    ros-humble-cartographer-ros \
    ros-humble-rviz2 \
    ros-humble-rmw-cyclonedds-cpp \
 && rm -rf /var/lib/apt/lists/*

ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
WORKDIR /ws
COPY entrypoint.bash /entrypoint.bash
ENTRYPOINT ["/entrypoint.bash"]

CMD ["bash","-lc","ros2 launch fastbot_slam cartographer.launch.py"]
